[package]
name = "decengine-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
fixture-engine = ["decengine-engine/fixture-engine"]

[dependencies]
decengine-compiler = { path = "../decengine-compiler" }
decengine-core = { path = "../decengine-core" }
decengine-engine = { path = "../decengine-engine" }
decengine-models = { path = "../decengine-models" }
parking_lot.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
